[tool.poetry]
name = "llm-airline-policy-app"
version = "0.1.0"
description = ""
authors = ["matprezru <matperrub@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
